'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace evacuk

    Partial Public Class vw_Products
        Inherits XPLiteObject
        Dim fproductId As Integer
        <Key()> _
        Public Property productId() As Integer
            Get
                Return fproductId
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("productId", fproductId, value)
            End Set
        End Property
        Dim fmicrositeId As Integer
        Public Property micrositeId() As Integer
            Get
                Return fmicrositeId
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("micrositeId", fmicrositeId, value)
            End Set
        End Property
        Dim flanguageCode As String
        <Size(10)> _
        Public Property languageCode() As String
            Get
                Return flanguageCode
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("languageCode", flanguageCode, value)
            End Set
        End Property
        Dim fname As String
        <Size(50)> _
        Public Property name() As String
            Get
                Return fname
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("name", fname, value)
            End Set
        End Property
        Dim fshortDescription As String
        <Size(250)> _
        Public Property shortDescription() As String
            Get
                Return fshortDescription
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("shortDescription", fshortDescription, value)
            End Set
        End Property
        Dim fdescription As String
        <Size(400)> _
        Public Property description() As String
            Get
                Return fdescription
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("description", fdescription, value)
            End Set
        End Property
        Dim ffeatures As String
        <Size(2000)> _
        Public Property features() As String
            Get
                Return ffeatures
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("features", ffeatures, value)
            End Set
        End Property
        Dim fincludes As String
        <Size(2000)> _
        Public Property includes() As String
            Get
                Return fincludes
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("includes", fincludes, value)
            End Set
        End Property
        Dim fheight As String
        <Size(50)> _
        Public Property height() As String
            Get
                Return fheight
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("height", fheight, value)
            End Set
        End Property
        Dim fwidth As String
        <Size(50)> _
        Public Property width() As String
            Get
                Return fwidth
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("width", fwidth, value)
            End Set
        End Property
        Dim fdepth As String
        <Size(50)> _
        Public Property depth() As String
            Get
                Return fdepth
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("depth", fdepth, value)
            End Set
        End Property
        Dim fweight As String
        <Size(50)> _
        Public Property weight() As String
            Get
                Return fweight
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("weight", fweight, value)
            End Set
        End Property
        Dim floadCapacity As String
        <Size(50)> _
        Public Property loadCapacity() As String
            Get
                Return floadCapacity
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("loadCapacity", floadCapacity, value)
            End Set
        End Property
        Dim fvideo As String
        <Size(255)> _
        Public Property video() As String
            Get
                Return fvideo
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("video", fvideo, value)
            End Set
        End Property
        Dim fcertificate As String
        <Size(255)> _
        Public Property certificate() As String
            Get
                Return fcertificate
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("certificate", fcertificate, value)
            End Set
        End Property
        Dim fimage As String
        <Size(255)> _
        Public Property image() As String
            Get
                Return fimage
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("image", fimage, value)
            End Set
        End Property
        Dim faccessory As Boolean
        Public Property accessory() As Boolean
            Get
                Return faccessory
            End Get
            Set(ByVal value As Boolean)
                SetPropertyValue(Of Boolean)("accessory", faccessory, value)
            End Set
        End Property
        Dim fvideoBase As String
        <Size(255)> _
        Public Property videoBase() As String
            Get
                Return fvideoBase
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("videoBase", fvideoBase, value)
            End Set
        End Property
        Dim fproductCode As String
        <Size(15)> _
        Public Property productCode() As String
            Get
                Return fproductCode
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("productCode", fproductCode, value)
            End Set
        End Property
        Dim fevacAid As Boolean
        Public Property evacAid() As Boolean
            Get
                Return fevacAid
            End Get
            Set(ByVal value As Boolean)
                SetPropertyValue(Of Boolean)("evacAid", fevacAid, value)
            End Set
        End Property
        Dim fdisplayOrder As Integer
        Public Property displayOrder() As Integer
            Get
                Return fdisplayOrder
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("displayOrder", fdisplayOrder, value)
            End Set
        End Property
        Dim fvisible As Boolean
        Public Property visible() As Boolean
            Get
                Return fvisible
            End Get
            Set(ByVal value As Boolean)
                SetPropertyValue(Of Boolean)("visible", fvisible, value)
            End Set
        End Property
        Dim fstairclimber As Boolean
        Public Property stairclimber() As Boolean
            Get
                Return fstairclimber
            End Get
            Set(ByVal value As Boolean)
                SetPropertyValue(Of Boolean)("stairclimber", fstairclimber, value)
            End Set
        End Property
        Dim fbuildingmanagement As Boolean
        Public Property buildingmanagement() As Boolean
            Get
                Return fbuildingmanagement
            End Get
            Set(ByVal value As Boolean)
                SetPropertyValue(Of Boolean)("buildingmanagement", fbuildingmanagement, value)
            End Set
        End Property
        Dim fdatasheet As String
        <Size(50)> _
        Public Property datasheet() As String
            Get
                Return fdatasheet
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("datasheet", fdatasheet, value)
            End Set
        End Property
    End Class

End Namespace
