'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Drawing

Namespace Esso.Data

    Public Class FieldOption
        Inherits XPCustomObject
        Public Sub New(ByVal session As Session)
            MyBase.New(session)
        End Sub
        <Persistent("Oid"), Key(True), Browsable(False), MemberDesignTimeVisibility(False)>
        Private _Oid As Guid = Guid.Empty
        <PersistentAlias("_Oid"), Browsable(False)>
        Public ReadOnly Property Oid() As Guid
            Get
                Return _Oid
            End Get
        End Property
        Protected Overrides Sub OnSaving()
            MyBase.OnSaving()
            If Not (TypeOf Session Is NestedUnitOfWork) AndAlso Session.IsNewObject(Me) Then
                _Oid = XpoDefault.NewGuid()
            End If
        End Sub
        Private _Id As Integer
        Public Property ID() As Integer
            Get
                Return _Id
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("ID", _Id, value)
            End Set
        End Property
        Private _serviceField As eServiceFields
        Public Property ServiceField() As eServiceFields
            Get
                Return _serviceField
            End Get
            Set(ByVal value As eServiceFields)
                SetPropertyValue(Of eServiceFields)("ServiceField", _serviceField, value)
            End Set
        End Property
        Private _description As String
        Public Property Description() As String
            Get
                Return _description
            End Get
            Set(value As String)
                _description = value
            End Set
        End Property
    End Class

    Public Class Asset
        Inherits XPCustomObject
        Public Sub New(ByVal session As Session)
            MyBase.New(session)
        End Sub
        <Persistent("Oid"), Key(True), Browsable(False), MemberDesignTimeVisibility(False)>
        Private _Oid As Guid = Guid.Empty
        <PersistentAlias("_Oid"), Browsable(False)>
        Public ReadOnly Property Oid() As Guid
            Get
                Return _Oid
            End Get
        End Property
        Protected Overrides Sub OnSaving()
            MyBase.OnSaving()
            If Not (TypeOf Session Is NestedUnitOfWork) AndAlso Session.IsNewObject(Me) Then
                _Oid = XpoDefault.NewGuid()
            End If
        End Sub
        Private _division As Division
        <Association("Division-Assets")>
        Public Property Division() As Division
            Get
                Return _division
            End Get
            Set(ByVal value As Division)
                SetPropertyValue(Of Division)("Division", _division, value)
            End Set
        End Property
        Private _building As Building
        Public Property Building() As Building
            Get
                Return _building
            End Get
            Set(value As Building)
                SetPropertyValue(Of Building)("Building", _building, value)
            End Set
        End Property
        Private _barcode As String
        <Size(20)> _
        Public Property BarCode() As String
            Get
                Return _barcode
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("BarCode", _barcode, value)
            End Set
        End Property
        Private _product As Product
        Public Property Product() As Product
            Get
                Return _product
            End Get
            Set(value As Product)
                SetPropertyValue(Of Product)("Product", _product, value)
            End Set
        End Property
        Private _installed As Date
        Public Property Installed() As Date
            Get
                Return _installed
            End Get
            Set(value As Date)
                SetPropertyValue(Of Date)("Installed", _installed, value)
            End Set
        End Property
        Private _lastServiced As Date?
        Public Property LastServiced() As Date?
            Get
                Return _lastServiced
            End Get
            Set(value As Date?)
                SetPropertyValue(Of Date)("LastServiced", _lastServiced, value)
            End Set
        End Property
        Private _notes As String
        <Size(SizeAttribute.Unlimited)> _
           Public Property Notes() As String
            Get
                Return _notes
            End Get
            Set(value As String)
                SetPropertyValue(Of String)("LastServiced", _notes, value)
            End Set
        End Property
    End Class
  

End Namespace