'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Drawing

Namespace Esso.Data

    Public Class EvacService
        Inherits XPCustomObject
        Public Sub New(ByVal session As Session)
            MyBase.New(session)
        End Sub
        <Persistent("Oid"), Key(True), Browsable(False), MemberDesignTimeVisibility(False)>
        Private _Oid As Guid = Guid.Empty
        <PersistentAlias("_Oid"), Browsable(False)>
        Public ReadOnly Property Oid() As Guid
            Get
                Return _Oid
            End Get
        End Property
        Protected Overrides Sub OnSaving()
            MyBase.OnSaving()
            If Not (TypeOf Session Is NestedUnitOfWork) AndAlso Session.IsNewObject(Me) Then
                _Oid = XpoDefault.NewGuid()
            End If
        End Sub
        Private _diaryNo As Integer
        Public Property CentralDiaryNo() As Integer
            Get
                Return _diaryNo
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("CentralDiaryNo", _diaryNo, value)
            End Set
        End Property
        Private _division As Division
        Public Property Division() As Division
            Get
                Return _division
            End Get
            Set(ByVal value As Division)
                _division = value
            End Set
        End Property
        Private _contact As Contact
        Public Property Contact() As Contact
            Get
                Return _contact
            End Get
            Set(ByVal value As Contact)
                _contact = value
            End Set
        End Property
        Private _dateAttended As Date
        <DevExpress.Xpo.DisplayName("Date Attended")>
        Public Property DateAttended() As Date
            Get
                Return _dateAttended
            End Get
            Set(value As Date)
                SetPropertyValue(Of Date)("DateAttended", _dateAttended, value)
            End Set
        End Property
        Private _deniedAccess As Boolean
        Public Property DeniedAccess() As Boolean
            Get
                Return _deniedAccess
            End Get
            Set(value As Boolean)
                SetPropertyValue(Of Boolean)("DeniedAccess", _deniedAccess, value)
            End Set
        End Property
        Private _serviceDate As Date
        <DevExpress.Xpo.DisplayName("Service Date")>
        Public Property ServiceDate() As Date
            Get
                Return _serviceDate
            End Get
            Set(value As Date)
                SetPropertyValue(Of Date)("ServiceDate", _serviceDate, value)
            End Set
        End Property
        Private _signature As Image
        <DevExpress.Xpo.ValueConverter(GetType(DevExpress.Xpo.Metadata.ImageValueConverter))>
        Public Property Signature() As Image
            Get
                Return _signature
            End Get
            Set(ByVal value As Image)
                SetPropertyValue(Of Image)("Signature", _signature, value)
            End Set
        End Property
        Private _signer As String
        Public Property Signer() As String
            Get
                Return _signer
            End Get
            Set(value As String)
                SetPropertyValue(Of String)("Signer", _signer, value)
            End Set
        End Property
        <Association("Service-IBEX")>
        Public ReadOnly Property IbexServices() As XPCollection(Of IbexService)
            Get
                Return GetCollection(Of IbexService)("IbexServices")
            End Get
        End Property
        <Association("Service-CHAIRS")>
        Public ReadOnly Property ChairServices() As XPCollection(Of ChairService)
            Get
                Return GetCollection(Of ChairService)("ChairServices")
            End Get
        End Property
        Private _notes As String
        Public Property Notes() As String
            Get
                Return _notes
            End Get
            Set(value As String)
                SetPropertyValue(Of String)("Notes", _notes, value)
            End Set
        End Property
    End Class
    Public Class ChairService
        Inherits XPCustomObject
        Public Sub New(ByVal session As Session)
            MyBase.New(session)
        End Sub
        <Persistent("Oid"), Key(True), Browsable(False), MemberDesignTimeVisibility(False)>
        Private _Oid As Guid = Guid.Empty
        <PersistentAlias("_Oid"), Browsable(False)>
        Public ReadOnly Property Oid() As Guid
            Get
                Return _Oid
            End Get
        End Property
        Protected Overrides Sub OnSaving()
            MyBase.OnSaving()
            If Not (TypeOf Session Is NestedUnitOfWork) AndAlso Session.IsNewObject(Me) Then
                _Oid = XpoDefault.NewGuid()
            End If
        End Sub
        Private _evacService As EvacService
        <Association("Service-CHAIRS")>
        Public Property EvacService() As EvacService
            Get
                Return _evacService
            End Get
            Set(ByVal value As EvacService)
                _evacService = value
            End Set
        End Property
        Private _evacSurvey As EvacSurvey
        <Association("Survey-CHAIRS")>
        Public Property EvacSurvey() As EvacSurvey
            Get
                Return _evacSurvey
            End Get
            Set(ByVal value As EvacSurvey)
                _evacSurvey = value
            End Set
        End Property
        Private _building As Building
        Public Property Building() As Building
            Get
                Return _building
            End Get
            Set(value As Building)
                SetPropertyValue(Of Building)("Building", _building, value)
            End Set
        End Property
        Private _asset As Asset
        <Association("Asset-ChairServices")>
           Public Property Asset() As Asset
            Get
                Return _asset
            End Get
            Set(value As Asset)
                SetPropertyValue(Of Asset)("Asset", _asset, value)
            End Set
        End Property
        Private _serviceDate As Date
        Public Property ServiceDate() As Date
            Get
                Return _serviceDate
            End Get
            Set(value As Date)
                SetPropertyValue(Of Date)("ServiceDate", _serviceDate, value)
            End Set
        End Property
        Private _PlasticBushes As Char
        <DevExpress.Xpo.DisplayName("PlasticBushes")>
        Public Property PlasticBushes() As Char
            Get
                Return _PlasticBushes
            End Get
            Set(value As Char)
                SetPropertyValue(Of Char)("PlasticBushes", _PlasticBushes, value)
            End Set
        End Property
        Private _springClips As Boolean
        <DevExpress.Xpo.DisplayName("SpringClips")>
        Public Property SpringClips() As Boolean
            Get
                Return _springClips
            End Get
            Set(value As Boolean)
                SetPropertyValue(Of Boolean)("SpringClips", _springClips, value)
            End Set
        End Property
        Private _passengerBelt As Boolean
        <DevExpress.Xpo.DisplayName("PassengerBelt")>
        Public Property PassengerBelt() As Boolean
            Get
                Return PassengerBelt
            End Get
            Set(value As Boolean)
                SetPropertyValue(Of Boolean)("PassengerBelt", _passengerBelt, value)
            End Set
        End Property
        Private _hammockSeatPadding As Boolean
        <DevExpress.Xpo.DisplayName("HammockSeatPadding")>
        Public Property HammockSeatPadding() As Boolean
            Get
                Return _hammockSeatPadding
            End Get
            Set(value As Boolean)
                SetPropertyValue(Of Boolean)("HammockSeatPadding", _hammockSeatPadding, value)
            End Set
        End Property
        Private _headRestraint As Boolean
        <DevExpress.Xpo.DisplayName("HeadRestraint")>
        Public Property HeadRestraint() As Boolean
            Get
                Return _headRestraint
            End Get
            Set(value As Boolean)
                SetPropertyValue(Of Boolean)("HeadRestraint", _headRestraint, value)
            End Set
        End Property
        Private _trolleyAssemblyandClips As Boolean
        <DevExpress.Xpo.DisplayName("TrolleyAssemblyandClips")>
        Public Property TrolleyAssemblyandClips() As Boolean
            Get
                Return _trolleyAssemblyandClips
            End Get
            Set(value As Boolean)
                SetPropertyValue(Of Boolean)("TrolleyAssemblyandClips", _trolleyAssemblyandClips, value)
            End Set
        End Property
        Private _skiAssemblyRollers As Boolean
        <DevExpress.Xpo.DisplayName("SkiAssemblyRollers")>
        Public Property SkiAssemblyRollers() As Boolean
            Get
                Return _skiAssemblyRollers
            End Get
            Set(value As Boolean)
                SetPropertyValue(Of Boolean)("SkiAssemblyRollers", _skiAssemblyRollers, value)
            End Set
        End Property
        Private _beltsRotationTension As Boolean
        <DevExpress.Xpo.DisplayName("Belts Rotation Tension")>
        Public Property BeltsRotationTension() As Boolean
            Get
                Return _beltsRotationTension
            End Get
            Set(value As Boolean)
                SetPropertyValue(Of Boolean)("BeltsRotationTension", _beltsRotationTension, value)
            End Set
        End Property
        Private _tractionBeltsHighChange As Boolean
        <DevExpress.Xpo.DisplayName("TractionBeltsHighChange")>
        Public Property TractionBeltsHighChange() As Boolean
            Get
                Return _tractionBeltsHighChange
            End Get
            Set(value As Boolean)
                SetPropertyValue(Of Boolean)("TractionBeltsHighChange", _tractionBeltsHighChange, value)
            End Set
        End Property
        Private _mainWheelsMoveFreely As Boolean
        <DevExpress.Xpo.DisplayName("Main Wheels Move Freely")>
        Public Property MainWheelsMoveFreely() As Boolean
            Get
                Return _mainWheelsMoveFreely
            End Get
            Set(value As Boolean)
                SetPropertyValue(Of Boolean)("MainWheelsMoveFreely", _mainWheelsMoveFreely, value)
            End Set
        End Property

        Private _CheckRivets As Boolean
        <DevExpress.Xpo.DisplayName("CheckRivets")>
        Public Property CheckRivets() As Boolean
            Get
                Return _CheckRivets
            End Get
            Set(value As Boolean)
                SetPropertyValue(Of Boolean)("CheckRivets", _CheckRivets, value)
            End Set
        End Property
        Private _PaddingSeat As Boolean
        <DevExpress.Xpo.DisplayName("PaddingSeat")>
        Public Property PaddingSeat() As Boolean
            Get
                Return _CheckRivets
            End Get
            Set(value As Boolean)
                SetPropertyValue(Of Boolean)("PaddingSeat", _PaddingSeat, value)
            End Set
        End Property

        Private _FrontHandle As Boolean
        <DevExpress.Xpo.DisplayName("FrontHandle")>
        Public Property FrontHandle() As Boolean
            Get
                Return _FrontHandle
            End Get
            Set(value As Boolean)
                SetPropertyValue(Of Boolean)("FrontHandle", _FrontHandle, value)
            End Set
        End Property
        Private _RearHandle As Boolean
        <DevExpress.Xpo.DisplayName("RearHandle")>
        Public Property RearHandle() As Boolean
            Get
                Return _RearHandle
            End Get
            Set(value As Boolean)
                SetPropertyValue(Of Boolean)("RearHandle", _RearHandle, value)
            End Set
        End Property
        Private _HammockCondition As Boolean
        <DevExpress.Xpo.DisplayName("HammockCondition")>
        Public Property HammockCondition() As Boolean
            Get
                Return _HammockCondition
            End Get
            Set(value As Boolean)
                SetPropertyValue(Of Boolean)("HammockCondition", _HammockCondition, value)
            End Set
        End Property
        Private _KickstandGasSpring As Boolean
        <DevExpress.Xpo.DisplayName("KickstandGasSpring")>
        Public Property KickstandGasSpring() As Boolean
            Get
                Return _KickstandGasSpring
            End Get
            Set(value As Boolean)
                SetPropertyValue(Of Boolean)("KickstandGasSpring", _KickstandGasSpring, value)
            End Set
        End Property
        Private _RotationBelts As Boolean
        <DevExpress.Xpo.DisplayName("RotationBelts")>
        Public Property RotationBelts() As Boolean
            Get
                Return _RotationBelts
            End Get
            Set(value As Boolean)
                SetPropertyValue(Of Boolean)("RotationBelts", _RotationBelts, value)
            End Set
        End Property
        Private _SpindlePosition As Boolean
        <DevExpress.Xpo.DisplayName("SpindlePosition")>
        Public Property SpindlePosition() As Boolean
            Get
                Return _SpindlePosition
            End Get
            Set(value As Boolean)
                SetPropertyValue(Of Boolean)("SpindlePosition", _SpindlePosition, value)
            End Set
        End Property
        Private _SafetyBelt As Boolean
        <DevExpress.Xpo.DisplayName("SafetyBelt")>
        Public Property SafetyBelt() As Boolean
            Get
                Return _SafetyBelt
            End Get
            Set(value As Boolean)
                SetPropertyValue(Of Boolean)("SafetyBelt", _SafetyBelt, value)
            End Set
        End Property
        Private _SeatFrame As Boolean
        <DevExpress.Xpo.DisplayName("SeatFrame")>
        Public Property SeatFrame() As Boolean
            Get
                Return _SeatFrame
            End Get
            Set(value As Boolean)
                SetPropertyValue(Of Boolean)("SeatFrame", _SeatFrame, value)
            End Set
        End Property
        Private _KickstandBolt As Boolean
        <DevExpress.Xpo.DisplayName("KickstandBolt")>
        Public Property KickstandBolt() As Boolean
            Get
                Return _KickstandBolt
            End Get
            Set(value As Boolean)
                SetPropertyValue(Of Boolean)("KickstandBolt", _KickstandBolt, value)
            End Set
        End Property
        Private _KickstandGas As Boolean
        <DevExpress.Xpo.DisplayName("KickstandGas")>
        Public Property KickstandGas() As Boolean
            Get
                Return _KickstandGas
            End Get
            Set(value As Boolean)
                SetPropertyValue(Of Boolean)("KickstandGas", _KickstandGas, value)
            End Set
        End Property
        Private _StabiliserRivets As Boolean
        <DevExpress.Xpo.DisplayName("StabiliserRivets")>
        Public Property StabiliserRivets() As Boolean
            Get
                Return _StabiliserRivets
            End Get
            Set(value As Boolean)
                SetPropertyValue(Of Boolean)("StabiliserRivets", _StabiliserRivets, value)
            End Set
        End Property
        Private _Closure As Boolean
        <DevExpress.Xpo.DisplayName("Closure")>
        Public Property Closure() As Boolean
            Get
                Return _Closure
            End Get
            Set(value As Boolean)
                SetPropertyValue(Of Boolean)("Closure", _Closure, value)
            End Set
        End Property
        Private _levelGroundMovement As Boolean
        <DevExpress.Xpo.DisplayName("Level Ground Movement")>
        Public Property LevelGroundMovement() As Boolean
            Get
                Return _levelGroundMovement
            End Get
            Set(value As Boolean)
                SetPropertyValue(Of Boolean)("LevelGroundMovement", _levelGroundMovement, value)
            End Set
        End Property
        Private _dustCoverinPlace As Boolean
        <DevExpress.Xpo.DisplayName("Dust Cover in Place")>
        Public Property DustCoverinPlace() As Boolean
            Get
                Return _dustCoverinPlace
            End Get
            Set(value As Boolean)
                SetPropertyValue(Of Boolean)("DustCoverinPlace", _dustCoverinPlace, value)
            End Set
        End Property
        Private _wallHooksFitted As Boolean
        <DevExpress.Xpo.DisplayName("Wall Hooks Fitted")>
        Public Property WallHooksFitted() As Boolean
            Get
                Return _wallHooksFitted
            End Get
            Set(value As Boolean)
                SetPropertyValue(Of Boolean)("WallHooksFitted", _wallHooksFitted, value)
            End Set
        End Property
        Private _signageinPlace As Boolean
        <DevExpress.Xpo.DisplayName("SignageinPlace")>
        Public Property SignageinPlace() As Boolean
            Get
                Return _signageinPlace
            End Get
            Set(value As Boolean)
                SetPropertyValue(Of Boolean)("SignageinPlace", _signageinPlace, value)
            End Set
        End Property
        Private _alarmFitted As Boolean
        <DevExpress.Xpo.DisplayName("Alarm Fitted")>
        Public Property AlarmFitted() As Boolean
            Get
                Return _alarmFitted
            End Get
            Set(value As Boolean)
                SetPropertyValue(Of Boolean)("AlarmFitted", _alarmFitted, value)
            End Set
        End Property
        Private _ACOP As Boolean
        <DevExpress.Xpo.DisplayName("ACOP")>
        Public Property ACOP() As Boolean
            Get
                Return _alarmFitted
            End Get
            Set(value As Boolean)
                SetPropertyValue(Of Boolean)("ACOP", _ACOP, value)
            End Set
        End Property
        Private _paddedWoodenSeat As Boolean
        <DevExpress.Xpo.DisplayName("Padded Wooden Seat")>
        Public Property PaddedWoodenSeat() As Boolean
            Get
                Return _paddedWoodenSeat
            End Get
            Set(value As Boolean)
                SetPropertyValue(Of Boolean)("PaddedWoodenSeat", _paddedWoodenSeat, value)
            End Set
        End Property
        Private _dustedChair As Boolean
        <DevExpress.Xpo.DisplayName("Dusted Chair")>
        Public Property DustedChair() As Boolean
            Get
                Return _dustedChair
            End Get
            Set(value As Boolean)
                SetPropertyValue(Of Boolean)("DustedChair", _dustedChair, value)
            End Set
        End Property
        Private _passFail As Boolean
        <DevExpress.Xpo.DisplayName("Pass/Fail")>
        Public Property PassFail() As Boolean
            Get
                Return _passFail
            End Get
            Set(value As Boolean)
                SetPropertyValue(Of Boolean)("PassFail", _passFail, value)
            End Set
        End Property
        Private _notes As String
        Public Property Notes() As String
            Get
                Return _notes
            End Get
            Set(value As String)
                SetPropertyValue(Of String)("Notes", _notes, value)
            End Set
        End Property
    End Class
    Public Class IbexService
        Inherits XPCustomObject
        Public Sub New(ByVal session As Session)
            MyBase.New(session)
        End Sub
        <Persistent("Oid"), Key(True), Browsable(False), MemberDesignTimeVisibility(False)>
        Private _Oid As Guid = Guid.Empty
        <PersistentAlias("_Oid"), Browsable(False)>
        Public ReadOnly Property Oid() As Guid
            Get
                Return _Oid
            End Get
        End Property
        Protected Overrides Sub OnSaving()
            MyBase.OnSaving()
            If Not (TypeOf Session Is NestedUnitOfWork) AndAlso Session.IsNewObject(Me) Then
                _Oid = XpoDefault.NewGuid()
            End If
        End Sub
        Private _evacService As EvacService
        <Association("Service-IBEX")>
        Public Property EvacService() As EvacService
            Get
                Return _evacService
            End Get
            Set(ByVal value As EvacService)
                _evacService = value
            End Set
        End Property
        Private _building As Building
        Public Property Building() As Building
            Get
                Return _building
            End Get
            Set(value As Building)
                SetPropertyValue(Of Building)("Building", _building, value)
            End Set
        End Property
        Private _asset As Asset
        Public Property Asset() As Asset
            Get
                Return _asset
            End Get
            Set(value As Asset)
                SetPropertyValue(Of Asset)("Asset", _asset, value)
            End Set
        End Property
        Private _serviceDate As Date
        Public Property ServiceDate() As Date
            Get
                Return _serviceDate
            End Get
            Set(value As Date)
                SetPropertyValue(Of Date)("ServiceDate", _serviceDate, value)
            End Set
        End Property
        Private _Fasteners As Char
        <DevExpress.Xpo.DisplayName("Fasteners")>
        Public Property Fasteners() As Char
            Get
                Return _Fasteners
            End Get
            Set(value As Char)
                SetPropertyValue(Of Char)("Fasteners", _Fasteners, value)
            End Set
        End Property
        Private _fastenersOpt As FieldOption
        <DevExpress.Xpo.DisplayName("Fasteners")>
        Public Property FastenersOpt() As FieldOption
            Get
                Return _fastenersOpt
            End Get
            Set(value As FieldOption)
                SetPropertyValue(Of FieldOption)("FastenersOpt", _fastenersOpt, value)
            End Set
        End Property
        Private _BrakeMechanism As Char
        <DevExpress.Xpo.DisplayName("BrakeMechanism")>
        Public Property BrakeMechanism() As Char
            Get
                Return _BrakeMechanism
            End Get
            Set(value As Char)
                SetPropertyValue(Of Char)("BrakeMechanism", _BrakeMechanism, value)
            End Set
        End Property
        Private _BrakeMechanismOpt As FieldOption
        Public Property BrakeMechanismOpt() As FieldOption
            Get
                Return _BrakeMechanismOpt
            End Get
            Set(value As FieldOption)
                SetPropertyValue(Of FieldOption)("BrakeMechanismOpt", _BrakeMechanismOpt, value)
            End Set
        End Property
        Private _handGrips As Char
        <DevExpress.Xpo.DisplayName("HandGrips")>
        Public Property HandGrips() As Char
            Get
                Return _handGrips
            End Get
            Set(value As Char)
                SetPropertyValue(Of Char)("HandGrips", _handGrips, value)
            End Set
        End Property
        Private _HandGripsOpt As FieldOption
        Public Property HandGripsOpt() As FieldOption
            Get
                Return _HandGripsOpt
            End Get
            Set(value As FieldOption)
                SetPropertyValue(Of FieldOption)("HandGripsOpt", _HandGripsOpt, value)
            End Set
        End Property
        Private _PlugsCaps As Char
        <DevExpress.Xpo.DisplayName("PlugsCaps")>
        Public Property PlugsCaps() As Char
            Get
                Return _PlugsCaps
            End Get
            Set(value As Char)
                SetPropertyValue(Of Char)("PlugsCaps", _PlugsCaps, value)
            End Set
        End Property
        Private _PlugsCapsOpt As FieldOption
        Public Property PlugsCapsOpt() As FieldOption
            Get
                Return _PlugsCapsOpt
            End Get
            Set(value As FieldOption)
                SetPropertyValue(Of FieldOption)("PlugsCapsOpt", _PlugsCapsOpt, value)
            End Set
        End Property
        Private _BackRest As Char
        <DevExpress.Xpo.DisplayName("BackRest")>
        Public Property BackRest() As Char
            Get
                Return _BackRest
            End Get
            Set(value As Char)
                SetPropertyValue(Of Char)("BackRest", _BackRest, value)
            End Set
        End Property
        Private _BackRestOpt As FieldOption
        Public Property BackRestOpt() As FieldOption
            Get
                Return _BackRestOpt
            End Get
            Set(value As FieldOption)
                SetPropertyValue(Of FieldOption)("BackRestOpt", _BackRestOpt, value)
            End Set
        End Property
        Private _PatientStraps As Char
        <DevExpress.Xpo.DisplayName("PatientStraps")>
        Public Property PatientStraps() As Char
            Get
                Return _PatientStraps
            End Get
            Set(value As Char)
                SetPropertyValue(Of Char)("PatientStraps", _PatientStraps, value)
            End Set
        End Property
        Private _patientStrapsOpt As FieldOption
        Public Property PatientStrapsOpt() As FieldOption
            Get
                Return _patientStrapsOpt
            End Get
            Set(value As FieldOption)
                SetPropertyValue(Of FieldOption)("PatientStrapsOpt", _patientStrapsOpt, value)
            End Set
        End Property
        Private _WheelPulleys As Char
        <DevExpress.Xpo.DisplayName("WheelPulleys")>
        Public Property WheelPulleys() As Char
            Get
                Return _WheelPulleys
            End Get
            Set(value As Char)
                SetPropertyValue(Of Char)("WheelPulleys", _WheelPulleys, value)
            End Set
        End Property
        Private _WheelPulleysOpt As Char
        Public Property WheelPulleysOpt() As Char
            Get
                Return _WheelPulleysOpt
            End Get
            Set(value As Char)
                SetPropertyValue(Of Char)("WheelPulleysOpt", _WheelPulleysOpt, value)
            End Set
        End Property
        Private _Telescopic As Char
        Public Property Telescopic() As Char
            Get
                Return _Telescopic
            End Get
            Set(value As Char)
                SetPropertyValue(Of Char)("Telescopic", _Telescopic, value)
            End Set
        End Property
        Private _TelescopicOpt As FieldOption
        Public Property TelescopicOpt() As FieldOption
            Get
                Return _TelescopicOpt
            End Get
            Set(value As FieldOption)
                SetPropertyValue(Of FieldOption)("TelescopicOpt", _TelescopicOpt, value)
            End Set
        End Property
        Private _pass As Char
        <DevExpress.Xpo.DisplayName("Pass/Fail")>
        Public Property Pass() As Char
            Get
                Return _pass
            End Get
            Set(value As Char)
                SetPropertyValue(Of Char)("Pass", _pass, value)
            End Set
        End Property

        Private _notes As String
        Public Property Notes() As String
            Get
                Return _notes
            End Get
            Set(value As String)
                SetPropertyValue(Of String)("Notes", _notes, value)
            End Set
        End Property
    End Class

End Namespace