'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Drawing
Imports DevExpress.Xpo.DB

Namespace Esso.Data
    Public Class EvacSurvey
        Inherits XPCustomObject
        Public Sub New(ByVal session As Session)
            MyBase.New(session)
        End Sub
        <Persistent("Oid"), Key(True), Browsable(False), MemberDesignTimeVisibility(False)>
        Private _Oid As Guid = Guid.Empty
        <PersistentAlias("_Oid"), Browsable(False)>
        Public ReadOnly Property Oid() As Guid
            Get
                Return _Oid
            End Get
        End Property
        Protected Overrides Sub OnSaving()
            MyBase.OnSaving()
            If Not (TypeOf Session Is NestedUnitOfWork) AndAlso Session.IsNewObject(Me) Then
                _Oid = XpoDefault.NewGuid()
            End If
        End Sub
        Private _division As Division
        Public Property Division() As Division
            Get
                Return _division
            End Get
            Set(ByVal value As Division)
                SetPropertyValue(Of Division)("Division", _division, value)
            End Set
        End Property
        Private _contact As Contact
        Public Property Contact() As Contact
            Get
                Return _contact
            End Get
            Set(ByVal value As Contact)
                SetPropertyValue(Of Contact)("Contact", _contact, value)
            End Set
        End Property
        Private _surveyBy As User
        Public Property SurveyBy() As User
            Get
                Return _surveyBy
            End Get
            Set(value As User)
                SetPropertyValue(Of User)("SurveyBy", _surveyBy, value)
            End Set
        End Property
        Private _surveyDate As Date
        <DevExpress.Xpo.DisplayName("Survey Date")>
        Public Property SurveyDate() As Date
            Get
                Return _surveyDate
            End Get
            Set(value As Date)
                SetPropertyValue(Of Date)("SurveyDate", _surveyDate, value)
            End Set
        End Property
        Private _access As String
        <Size(20)>
        Public Property Access() As String
            Get
                Return _access
            End Get
            Set(value As String)
                SetPropertyValue(Of String)("Access", _access, value)
            End Set
        End Property
        Private _heritage As String
        Public Property Heritage() As String
            Get
                Return _heritage
            End Get
            Set(value As String)
                SetPropertyValue(Of String)("Heritage", _heritage, value)
            End Set
        End Property
        Public ReadOnly Property HasHeritage() As Integer
            Get
                Return Convert.ToInt32(Session.Evaluate(Of Building)(CriteriaOperator.Parse("Count()"), CriteriaOperator.Parse("Division = ? and Heritage='Y'", Division)))
            End Get
        End Property
        Public ReadOnly Property HasHospital() As Integer
            Get
                Return Convert.ToInt32(Session.Evaluate(Of Building)(CriteriaOperator.Parse("Count()"), CriteriaOperator.Parse("Division = ? and Hospital=?", Division, "Y")))
            End Get
        End Property
        Public ReadOnly Property HasEducational() As Integer
            Get
                Return Convert.ToInt32(Session.Evaluate(Of Building)(CriteriaOperator.Parse("Count()"), CriteriaOperator.Parse("Division = ? and Educational='Y'", Division)))
            End Get
        End Property
        Public ReadOnly Property ReportOptions() As String

            Get
                Dim _ret As String = String.Empty

                If HasHeritage > 0 Then
                    _ret += String.Format("{0} {1}", Session.FindObject(Of ReportOption)(CriteriaOperator.Parse("OptNo= 1")).Text, Environment.NewLine)
                End If
                If HasHospital > 0 Then
                    _ret += String.Format("{0} {1}", Session.FindObject(Of ReportOption)(CriteriaOperator.Parse("OptNo= 2")).Text, Environment.NewLine)
                End If
                If HasEducational > 0 Then
                    _ret += String.Format("{0} {1}", Session.FindObject(Of ReportOption)(CriteriaOperator.Parse("OptNo= 3")).Text, Environment.NewLine)
                End If
                Return _ret.TrimEnd
            End Get
        End Property
        Private _escapeRoutes As Integer
        Public Property EscapeRoutes() As Integer
            Get
                Return _escapeRoutes
            End Get
            Set(value As Integer)
                SetPropertyValue(Of Integer)("EscapeRoutes", _escapeRoutes, value)
            End Set
        End Property
        <Association("Survey-Floors")>
        Public ReadOnly Property Floors() As XPCollection(Of Floor)
            Get
                Return GetCollection(Of Floor)("Floors")
            End Get
        End Property

        Private _signer As String
        Public Property Signer() As String
            Get
                Return _signer
            End Get
            Set(value As String)
                SetPropertyValue(Of String)("Signer", _signer, value)
            End Set
        End Property
        Private _notes As String
        Public Property Notes() As String
            Get
                Return _notes
            End Get
            Set(value As String)
                SetPropertyValue(Of String)("Notes", _notes, value)
            End Set
        End Property

        Public ReadOnly Property ProductsSummary() As XPDataView
            '''
            Get
                Return GetProductsSummary()
            End Get
        End Property
        Private Function GetProductsSummary() As XPDataView

            Dim _sql As String = ""

            Dim sSql As String = "SELECT  EvacSurvey.Oid, EvacSurvey.SurveyDate, EvacSurvey.Signer, EvacSurvey.Notes, "
            sSql += " Product.ProductCode, Building.Location, 1 as Quantity "
            sSql += "From EvacSurvey INNER Join "
            sSql += "Division On EvacSurvey.Division = Division.Oid INNER Join "
            sSql += "Building On Division.Oid = Building.Division INNER Join "
            sSql += "Floor On Building.Oid = Floor.Building INNER Join "
            sSql += "Product On Floor.Product = Product.Oid "
            sSql += String.Format("WHERE (EvacSurvey.Oid = '{0}')", Oid)


            Dim dv As New XPDataView()
            Dim data As SelectedData = Session.ExecuteQueryWithMetadata(_sql)
            For Each row As SelectStatementResultRow In data.ResultSet(0).Rows
                dv.AddProperty(DirectCast(row.Values(0), String), DBColumn.[GetType](DirectCast([Enum].Parse(GetType(DBColumnType), DirectCast(row.Values(2), String)), DBColumnType)))
            Next
            dv.LoadData(New SelectedData(data.ResultSet(1)))

            Return dv

        End Function
        Private fcreatedBy As User
        Public Property CreatedBy() As User
            Get
                Return fcreatedBy
            End Get
            Set(ByVal value As User)
                SetPropertyValue(Of User)("CreatedBy", fcreatedBy, value)
            End Set
        End Property
        Private fcreatedAt As DateTime
        Public Property CreatedAt() As DateTime
            Get
                Return fcreatedAt
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("CreatedAt", fcreatedAt, value)
            End Set
        End Property
        Private fmodifiedBy As User
        <MergeCollisionBehavior(OptimisticLockingReadMergeBehavior.Ignore)>
        Public Property ModifiedBy() As User
            Get
                Return fmodifiedBy
            End Get
            Set(ByVal value As User)
                SetPropertyValue(Of User)("ModifiedBy", fmodifiedBy, value)
            End Set
        End Property
        Private fmodifiedAt As DateTime
        <MergeCollisionBehavior(OptimisticLockingReadMergeBehavior.Ignore)>
        Public Property ModifiedAt() As DateTime
            Get
                Return fmodifiedAt
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("ModifiedAt", fmodifiedAt, value)
            End Set
        End Property

    End Class
End Namespace