'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Drawing

Namespace Esso.Data
    Public Class EvacSurvey
        Inherits XPCustomObject
        Public Sub New(ByVal session As Session)
            MyBase.New(session)
        End Sub
        <Persistent("Oid"), Key(True), Browsable(False), MemberDesignTimeVisibility(False)>
        Private _Oid As Guid = Guid.Empty
        <PersistentAlias("_Oid"), Browsable(False)>
        Public ReadOnly Property Oid() As Guid
            Get
                Return _Oid
            End Get
        End Property
        Protected Overrides Sub OnSaving()
            MyBase.OnSaving()
            If Not (TypeOf Session Is NestedUnitOfWork) AndAlso Session.IsNewObject(Me) Then
                _Oid = XpoDefault.NewGuid()
            End If
        End Sub
        Private _division As Division
        <Association("Division-Survey")>
        Public Property Division() As Division
            Get
                Return _division
            End Get
            Set(ByVal value As Division)
                SetPropertyValue(Of Division)("Division", _division, value)
            End Set
        End Property
        Private _contact As Contact
        Public Property Contact() As Contact
            Get
                Return _contact
            End Get
            Set(ByVal value As Contact)
                SetPropertyValue(Of Contact)("Contact", _contact, value)
            End Set
        End Property
        Private _surveyDate As Date
        <DevExpress.Xpo.DisplayName("Survey Date")>
        Public Property SurveyDate() As Date
            Get
                Return _surveyDate
            End Get
            Set(value As Date)
                SetPropertyValue(Of Date)("SurveyDate", _surveyDate, value)
            End Set
        End Property
        Private _access As String
        <Size(20)>
        Public Property Access() As String
            Get
                Return _access
            End Get
            Set(value As String)
                SetPropertyValue(Of String)("Access", _access, value)
            End Set
        End Property
        Private _heritage As String
        Public Property Heritage() As String
            Get
                Return _heritage
            End Get
            Set(value As String)
                SetPropertyValue(Of String)("Heritage", _heritage, value)
            End Set
        End Property
        Private _escapeRoutes As Integer
        Public Property EscapeRoutes() As Integer
            Get
                Return _escapeRoutes
            End Get
            Set(value As Integer)
                SetPropertyValue(Of Integer)("EscapeRoutes", _escapeRoutes, value)
            End Set
        End Property



        Private _signer As String
        Public Property Signer() As String
            Get
                Return _signer
            End Get
            Set(value As String)
                SetPropertyValue(Of String)("Signer", _signer, value)
            End Set
        End Property

        '<Association("Service-IBEX")>
        'Public ReadOnly Property IbexServices() As XPCollection(Of IbexService)
        '    Get
        '        Return GetCollection(Of IbexService)("IbexServices")
        '    End Get
        'End Property
        <Association("Survey-Buildings")>
          Public ReadOnly Property Buildings() As XPCollection(Of Building)
            Get
                Return GetCollection(Of Building)("Buildings")
            End Get
        End Property

        Private _notes As String
        Public Property Notes() As String
            Get
                Return _notes
            End Get
            Set(value As String)
                SetPropertyValue(Of String)("Notes", _notes, value)
            End Set
        End Property
        Private fcreatedBy As User
        Public Property CreatedBy() As User
            Get
                Return fcreatedBy
            End Get
            Set(ByVal value As User)
                SetPropertyValue(Of User)("CreatedBy", fcreatedBy, value)
            End Set
        End Property
        Private fcreatedAt As DateTime
        Public Property CreatedAt() As DateTime
            Get
                Return fcreatedAt
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("CreatedAt", fcreatedAt, value)
            End Set
        End Property
        Private fmodifiedBy As User
        <MergeCollisionBehavior(OptimisticLockingReadMergeBehavior.Ignore)>
        Public Property ModifiedBy() As User
            Get
                Return fmodifiedBy
            End Get
            Set(ByVal value As User)
                SetPropertyValue(Of User)("ModifiedBy", fmodifiedBy, value)
            End Set
        End Property
        Private fmodifiedAt As DateTime
        <MergeCollisionBehavior(OptimisticLockingReadMergeBehavior.Ignore)>
        Public Property ModifiedAt() As DateTime
            Get
                Return fmodifiedAt
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("ModifiedAt", fmodifiedAt, value)
            End Set
        End Property

    End Class
End Namespace